version: '3.4'

services:
  garbagegenerator:
    image: garbagegenerator
    build:
      context: .
      dockerfile: GarbageGenerator/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
