version: '3.4'

services:
  garbagegenerator:
    image: garbagegenerator
    logging:
      driver: none
    build:
      context: .
      dockerfile: GarbageGenerator/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://*:5000
        - to_power_of=20
        - name=1
    ports:
      - 5000
  gci-proxy:
    image: gciproxy
    environment:
      - flags=-gci_path=__gci -gci_target=garbagegenerator:5000 -target garbagegenerator:5000 -ygen=40108864
    ports:
      - 80:3000