version: '3.4'

services:
  garbagegenerator:
    image: garbagegenerator
    build:
      context: .
      dockerfile: GarbageGenerator/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000
  gci-proxy:
    image: gciproxy
    depends_on: 
      - garbagegenerator
    environment:
      - flags=-gci_path=__gci -gci_target=garbagegenerator:5000 -target garbagegenerator:5000 -ygen 67108864
    ports:
      - 3000:3000